# config.toml
project_id = "aimatch"

[api]
port = 54321

[db]
port = 54322

[studio]
port = 54323

[inbucket]
port = 54324

[storage]
file_size_limit = "50MiB"

[auth]
site_url = "http://localhost:3000"
additional_redirect_urls = [
  "aimatch://",
  "com.aimatch_react_native://",
  "localhost",
  "aimatch://**",
  "com.aimatch_react_native://**"
]
jwt_expiry = 3600
enable_signup = true

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = true
# 以下3行を採用
max_frequency = "1m0s"
otp_length = 6
otp_expiry = 3600

[auth.mfa]
max_enrolled_factors = 10

[auth.mfa.totp]
# 二段階認証は不要にする
enroll_enabled = false
verify_enabled = false

# 必要なら他のMFA種類(例: phone)もfalseにしておく
[auth.mfa.phone]
enroll_enabled = false
verify_enabled = false

[auth.external.apple]
enabled = false
client_id = ""
secret = ""
